# Generated by Django 5.0 on 2023-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
